app/assets/javascripts/modules/copy-content.js
app/assets/sass/application.scss
app/routes.js
app/views/about-your-organisation.html
app/views/about-your-organisation/edit.html
app/views/macros/macros.njk
app/views/organisation.html
app/views/request-access.html
generate.rb
lib/prototype_data.json

* Remove tabs from pages
* Put link to about your org on main body to make it more obvious and "in flow"
* Move request access down
* Make draft status orange to better represent incomplete state
* Represent statuses on the course and org pages

Improvements to about org flow, statuses and workflow

---

app/assets/sass/application.scss
app/assets/sass/components/_list.scss
app/routes.js
app/views/course/visa-sponsorship.html
app/views/new/_answers.html
app/views/preview.html

This adds an option for each course, to ask whether the provider can sponsor either a Skilled worker visa (for salaried courses) or a Student visa (for unsalaried courses). The answer given is summarised on the Basic details tab.
The preview of the page on Find has also been updated with a new "International students" section, which is populated with some text based upon the answer given to the Visa sponsorship question. Wording mostly taken from [Get into teaching](https://getintoteaching.education.gov.uk/international-candidates) and [GOV.UK](https://www.gov.uk/government/publications/train-to-teach-in-england-non-uk-applicants/train-to-teach-in-england-non-uk-applicants#visas-and-immigration) pages.

Add visa sponsorship question

---

app/views/preview.html

This updates the preview of the Find page to remove "EU students" as having the same fee as UK students, and instead link to a page on GOV.UK which described home fee eligibility.

EU students and home fee status eligibility

---

app/views/rolled-over.html

Previous cycles used an interstitial page to introduce the rollover period. This updates the content for the next cycle.

Rollover interstitial for 2021 to 2022

---

app/views/preview.html

Updates the Apply section to just be a start button, adds a missing "Support and advice" and renames the "Contact details" section to "Contact this training provider".

Update course preview to match production

---

app/views/macros/macros.njk

This might make it easier to user-test making changes to published courses (as otherwise you can't see how it’ll appear on Find)

Link "view online" to preview (for testing)

---

app/views/cycles.html
app/views/organisation/index.html
app/views/rolled-over.html
app/views/sign-in.html

This sets up the prototype for some user testing around the rollover flow and updating courses.
* Adds a basic sign in page to start from (`/sign-in`) which links to interstitial page
* Moves the "About your organisation" section to be cycle-specific
* Links to interstitial page from cycle page (in case users want to refer back to it)

Sign in - rollover flow

---

app/data/prototype-data.json

For some reason the prototype data contains both Gorse Scitt and Gorse SCITT - which meant that the list of courses was showing twice.

Bugfix with prototype data

---

app/data/prototype-data.json

Fixes this bug in the prototype setup, where there are two "About" rows

Bugfix: Gorse SCITT is self-accrediting

---

app/views/course/degree-subject.html

Some participants in user research didn't seem to understand that general guidance on degrees matching teaching subject would be shown. This might make that clearer?

Tweak question around degree subject requirements

---

app/views/course/gcses-pending-or-equivalency-tests.html
app/views/course/index.html

This might help providers to explain how equivalency tests work for them.

Add optional free text field for equivalency test details

---

app/views/cycles.html
app/views/location/index.html
app/views/locations/add.html
app/views/locations/index.html
app/views/locations/placements-display.html
app/views/locations/placements-policy.html
app/views/locations/upload.html
app/views/organisation/index.html
app/views/organisation/notification-enabled.html

- remove some repetition of 'current cycle', 'next cycle' etc.
- make definitions of 'placement schools' and 'training centres' into actions 
- make the choice between showing 'precise locations' and 'general areas' really clear by using these terms

Content changes locations

---

app/views/course/gcses-pending-or-equivalency-tests.html

Testing showed that some providers were reluctant to tick the subject boxes as they didn't run the equivalency tests themselves, but instead required candidates to use a third party.
This tweaked wording hopefully is generic enough to cover both cases, and the free text field uses the hint text to encourage providers to explain how they offer or require the tests to be taken. This is also now non-optional.

Update GCSE equivalency testing wording

---

app/views/course/index.html

Replaced 'offered' with 'accepted', as some providers accept but do not offer equivalency tests.

Update to equivalency test status

---

app/views/preview.html

Changed equivalency test status message from 'Equivalency tests offered' to 'Equivalency tests accepted' on preview.html page.

Changed 'offered' to 'accepted' on preview page

---

app/views/organisation/index.html

Re-worded the Request PE courses copy for the 'allocations open' condition so that it made more sense and was easier to read.
**BEFORE:**
**AFTER:**

Re-worded 'Request PE courses' copy

---

app/views/rolled-over.html

- made the intro a bit clearer
- changed the subheading to match the link in the call-to-action which appears on right hand side of university page
- made the bottom list a bulleted list instead of numbers (in line with GOV.UK style guide)

Content edits to Prepare for next cycle page

---

app/views/about-your-organisation/visa-sponsorship.html

Changed the "No" answer to "No, or not applicable" for providers who don't have salaried courses.
This change needs to be made to Publish in prod alongside the Visa sponsorship, degree requirements and GCSE/equivalency test changes. 
This change is in response to the UR findings. We discussed this in the Dev/Design session 30/6/21.

Content change to Skilled Worker visa answer

---

app/views/about-your-organisation/visa-sponsorship.html

This adds some more guidance, and changes the question wording.
For Skilled Worker visas, a "Only for some salaried courses" option has been added.
These changes are because we have learnt that, for Skilled Worker visas, these need to be sponsored by the employer, who in some cases will be different from the provider (in say, a teaching partnership). This means that it is possible that only some courses are able to sponsor visas. It could even be the case that within a single course, only some of the possible school placements are able to sponsor visas.
If the "Only for some salaried courses" option was selected, then we would have to make the guidance on the course page more equivocal, perhaps suggesting candidates get in touch with the provider to check before applying.
In future, if a …

Update visa sponsorship questions

---

app/content/course-summary-examples.md
app/content/writing-descriptions-for-publish-teacher-training-courses.md
app/controllers/courses.js
app/routes.js
app/views/_includes/footer.njk
app/views/courses/about-course.njk
app/views/guidance/index.njk
app/views/guidance/show.njk

- Change URL slug from `/guidance` to `/how-to-use-this-service`
- Remove inset text from the course summary page
- Remove 'How to publish teacher training courses' from the footer
- Change course summary word count back to 400 and row height to 20

Various fixes to the guidance pages

---

app/views/courses/description.njk
app/views/courses/details.njk
app/views/courses/vacancies/show.njk

Quick fix: `isCurrentCycle` and `isRolledOver` aren't true booleans but strings! 😬

Fix rolled over course banner logic

---

app/views/examples/course-names.njk
app/views/examples/index.njk

This PR adds:
- SEND to the course name examples
- primary course name examples
Examples can be found here: https://publish-tt-pr-411.herokuapp.com/examples/course-names

Add course name examples

---

app/routes.js

The prototype has an environment variable called `IS_ROLLOVER`.
When the prototype was upgraded to version 13, the environment variable was no longer passed through to the view. This meant things like the cycle switcher and phase banner did not display correctly.
This PR adds a variable to the `router.js` giving views access to the variable:
```javascript
res.locals.isRollover = process.env.IS_ROLLOVER || 'false'
```

Fix missing 'isRollover' variable
