DFE-Digital/publish-teacher-training-prototype

app/assets/sass/patterns/_course-parts.scss, app/routes.js, app/views/course.html, app/views/course/_errors.html, app/views/course/about-this-course.html, app/views/course/fees-and-length.html, app/views/course/requirements.html, app/views/history/course-not-running/index.html, app/views/macros/macros.njk, server.js
Plumb in validation checks on course publish
=> Make course validation work on publish

app/views/course-not-running.html, app/views/course.html, app/views/course/fees-and-length.html, app/views/macros/macros.njk, app/views/organisation.html, app/views/preview.html
* Port back copy tweaks
* Change not running banner to warning text
* Add "Other" field for course length
* Add line breaks for fees page
=> Bring prototype inline with live service

app/views/history/course-not-running-oct-15/index.html, app/views/history/course-not-running/index.html, app/views/history/index.html
=> Design history: course statuses iteration 15 October

app/views/history/location-research/index.html
This is an extension to #19 with some tidying of markup.
/cc @gemmasay
=> Add Gemma's provider insights write-up to the location research documentation

app/views/history/location-research/index.html
Added high level research findings from the provider round 5 testing. This adds in feedback from the "Find" map prototype (candidate facing) and also the "Publish" manage prototype, labelling the locations.
=> Added provider user research insights

app/routes.js, app/views/location.html, app/views/locations.html, app/views/macros/macros.njk
https://manage-courses-prototype.herokuapp.com/history/mvp-add-location
=> Use MVP location flow

app/assets/javascripts/map.js, app/assets/sass/application.scss, app/assets/sass/components/_map.scss, app/routes.js, app/utils/index.js, app/views/new-location/_answers.html, app/views/new-location/confirm.html
=> Add Maps to training locations flow

app/views/new/eligibility.html
https://manage-courses-prototype.herokuapp.com/history/minimum-requirements-iterations
=> Updated minimum requirements design with table

app/routes.js, app/views/location.html, app/views/locations.html, app/views/new/_answers.html, app/views/new/accredited-body.html, app/views/new/applications-open.html, app/views/new/further/_answers.html, app/views/new/start-date.html, app/views/new/training-locations.html, app/views/organisation.html, generate.rb, lib/prototype_data.json, server.js
* Use "locations" not "training locations"
* Add all accredited providers to drop down list in new course flow
* Add success message to locations
* Add validation to locations
https://manage-courses-prototype.herokuapp.com/history/mvp-add-location-iteration
=> Better locations

app/routes.js, app/utils/index.js, app/views/cycles.html, app/views/macros/macros.njk, app/views/organisation.html, app/views/rollover/_answers.html, app/views/rollover/confirm.html, app/views/rollover/courses.html, app/views/rollover/locations.html, app/views/rollover/start.html, generate.rb, lib/prototype_data.json
* Make pages forms
* Add locations
* Add check answers page
* Redirect to cycles
* Update org page for next/current cycle
=> Fake a full rollover process

README.md
About to do some work in this repo and noticed some update needed on the ReadMe.
=> URLs updated to point at Netlify

app/views/course/about-this-course.html, app/views/course/requirements.html
Show preview of structured guidance shown for:
* School placements
* Qualifications
=> Structured guidance

app/views/courses.html
Can we link this in now? Seems to be working?
=> Link to new course flow (instead of Google form)

app/views/course/index.html, app/views/course/vacancies-locations.html, app/views/course/vacancies.html, app/views/course/withdraw.html, app/views/locations/index.html, app/views/ucas/postal-address.html
This removes the references to UCAS being updated overnight.
=> Remove some of the UCAS references

app/views/preview.html
A few fixes to the preview, and updating some of the missing content boxes to link to the new questions.
=> Preview fixes

app/views/cycles.html, app/views/rolled-over.html, app/views/sign-in.html
=> Remove back link from interstitial after sign in

app/assets/sass/email.scss, app/data/prototype-data.json, app/utils.js, app/views/about-your-organisation/about.html, app/views/about-your-organisation/contact.html, app/views/about-your-organisation/index.html, app/views/about-your-organisation/placement-policy.html, app/views/course/index.html, app/views/email.html, app/views/emails/rollover.html, app/views/macros/macros.njk, app/views/new/_answers.html, app/views/new/placement-locations.html, app/views/preview.html, generate.rb
* Moving setting school placement policy to ‘About your organisation’
* Make ‘About your organisation’ function in the same way course details now function
* Use HEI for seed data (we can make a separate review app which uses this data)
* Add rollover email
=> New locations model, part 6

app/views/about-your-organisation/visa-sponsorship.html
Added hint text to make super clear how the visa questions apply to courses, as not all providers run both fee-paying and salaried courses.
=> Add hint text for visa questions

app/data/prototype-data.json, app/filters.js, app/views/course/gcses-pending-or-equivalency-tests.html, app/views/course/index.html, app/views/preview.html
Reverting back to something closer to [the original design](https://bat-design-history.netlify.app/publish-teacher-training-courses/minimum-course-requirements-logic).
=> Change GCSE equivalency questions

app/views/about-your-organisation/index.html, app/views/about-your-organisation/visa-sponsorship.html, app/views/preview.html
See https://www.gov.uk/skilled-worker-visa
=> Fix capitalisation of Skilled Worker visa

app/views/macros/macros.njk
...to avoid the awkwardness of "Preview on a course" as a heading.
=> Copy tweak

app/views/course/degree-level.html
Before:
> What is the minimum degree classification required?
After:
> What is the minimum degree classification you require?
=> Content change to minimum degree classification level question

app/views/organisation/index.html
front-load the content about the importance of adding locations
=> do some of the location selling up front

app/views/rolled-over.html
Lots of copy tweaks and improvements.
=> Update rollover interstitial following content review

app/views/preview.html
Copied across from [update to Find prototype](https://github.com/DFE-Digital/find-teacher-training-prototype/pull/45).
=> Content tweaks following review

app/helpers/courses.js
Add a special case for `3_to_11`
=> Fix age range label

app/controllers/vacancies.js, app/views/courses/_actions.njk, app/views/courses/vacancies/show.njk
Show change action if:
- course status is open or closed
Show rollover button if:
- is rollover
- is current cycle
- course not already rolled over
=> Fix course actions in vacancies section

app/controllers/courses.js, app/data/seed/funding-types.json, app/data/seed/qualifications.json, app/helpers/courses.js, app/views/courses/accredited-body.njk, app/views/courses/age-range.njk, app/views/courses/applications-open-date.njk, app/views/courses/check-your-answers.njk, app/views/courses/course-start.njk, app/views/courses/details.njk, app/views/courses/funding-type.njk, app/views/courses/location.njk, app/views/courses/qualification.njk, app/views/courses/subject-level.njk, app/views/courses/subject.njk, app/views/training-partners/courses/list.njk
See Trello card for changes: https://trello.com/c/APcXfOhx
=> Update add course flow content

app/views/organisations/details.njk, app/views/organisations/skilled-worker-visa.njk, app/views/organisations/student-visa.njk
See Trello https://trello.com/c/JHySgSGF
=> Update content on visa sponsorship

app/data/seed/financial-incentives.json, app/views/courses/check-your-answers.njk, app/views/courses/subject.njk
- Add 2023 bursary and scholarship information
- Move text about the first subject receiving the bursary or scholarship
- Change the layout of the subject page - move second subject out of details component
- Update check your answers page to show second subjects
=> Update bursary and scholarship information

app/controllers/courses.js, app/filters.js, app/helpers/courses.js, app/views/course-names.njk, app/views/courses/check-your-answers.njk, app/views/subjects.njk
- Add course title to check your answers page in Add course flow
- Update course name generator
- Add course name example page
- Update add course and edit course flows to use course new name generator
=> Add course title to check your answers page

app/controllers/authentication.js, app/controllers/cycles.js, app/controllers/organisations.js, app/controllers/settings.js, app/data/seed/settings.json, app/data/settings.json, app/models/settings.js, app/routes.js, app/views/_includes/footer.njk, app/views/settings/index.njk
This PR tests out an idea to add configurable settings to prototypes.
A similar approach can/will be used in other BAT prototypes.
Settings can be accessed via a link in the prototype's footer.
=> Add prototype settings
